version: '3.8'

services:
  postgres_keycloak:
    image: postgres:17
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    restart: always

  challenge-db:
    image: postgres:latest
    container_name: challenge-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres_keycloak
    restart: always

  challenge-veiculos-api:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_CONN_STR: jdbc:postgresql://challenge-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_ISSUER_URI: http://keycloak:8080/realms/challenge
      JWT_JWK_URI: http://keycloak:8080/realms/challenge/protocol/openid-connect/certs
    depends_on:
      - challenge-db
      - keycloak
    restart: always

volumes:
  pgdata_keycloak:
  pgdata:
